#!/bin/sh

/home/bendurham441/.config/bspwm/panel &
feh --bg-fill /home/bendurham441/.wallpaper.jpg
hsetroot -tile /home/bendurham441/Programming/white-cubes-pattern_1053-248.jpg -tint \#952bff -contrast 0.95
sxhkd -c /home/bendurham441/.config/sxhkd/sxhkdrc &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color \#151718
bspc config focused_border_color \#151718
#bspc config presel_feedback_color 
bspc config split_ratio 0.55
bspc config click_to_focus false
bspc config pointer_follows_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged monitors true

bspc config window_gap 15
bspc config border_width 15

